image: jeser/data-pipeline-ci

before_script:
    - apt-get update && apt-get -y upgrade  && apt-get -y install build-essential cmake clang git libcmocka-dev libglib2.0-dev ninja-build
    - mkdir build
    - cd build
    - export CC=clang
    - export CXX=clang++
    - cmake -G "Ninja" ..

stages:
  - build
  - test

build_gcc:
  stage: build
  script:
    - export CC=gcc
    - export CXX=g++
    - ninja

build_clang:
  stage: build
  script:
    - ninja

test_fast:
  stage: test
  script:
    - ninja
    - ninja test

test_devel:
  stage: test
  artifacts:
    paths:
        - build/Testing/
    when: on_failure
  script:
    - cmake -G "Ninja" -DDEVEL=true ..
    - ninja
    - ninja test

